server:
  port: 8080

spring:
  application:
    name: is1
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s367131
    password: pyN9STbCFkzue6Zy
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect